### ISSUE TITLE
CMakeList not found

### ISSUE THREAD

**Issue by lixiangnanyou** [MarcoSchaeferT/InVADo_setup#1]
I hope this message finds you well. I am currently trying to set up the InVADo project from the repository at https://github.com/MarcoSchaeferT/megamol-prolint-InVADo, but I have encountered an issue.

Upon downloading and extracting the repository, I noticed that the CMakeLists.txt file is missing from the F:\InVADo directory. This file is crucial for configuring and building the project using CMake.

Could you please verify if the CMakeLists.txt file is indeed missing? If so, would it be possible to add it to the repository? I would greatly appreciate your assistance with this matter, as it will help me and others in successfully building and running the InVADo project.

Thank you for your attention to this issue. I look forward to your response.

**Comment by MarcoSchaeferT** [comment]
Hello lixiangnanyou, all needed CMake files are present. You are already using the main repository of InVADO [InVADo Main](https://github.com/MarcoSchaeferT/megamol-prolint-InVADo) that stores the source code as described here: [InVADo Main Description](https://github.com/MarcoSchaeferT/InVADo_setup#main-repository-of-invado-httpsgithubcommarcoschaefertmegamol-prolint-invado) The current repository: [https://github.com/MarcoSchaeferT/InVADo_setup](https://github.com/MarcoSchaeferT/InVADo_setup) stores additional data and scripts, which are automatically merged with the main repository when running the CMake file of the main repository. (Further Info: InVADo is part of MegaMol ([InVADO Main](https://github.com/MarcoSchaeferT/megamol-prolint-InVADo)), which has a main [CMake file](https://github.com/MarcoSchaeferT/megamol-prolint-InVADo/blob/main/CMakeLists.txt) and additional ones for its plugins that are automatically used if the corresponding plugins are selected during the CMake configuration process: [building InVADo](https://github.com/MarcoSchaeferT/InVADo_setup#building-invado). InVADo is part of the PROLINT plugin that has the following CMake file: [Prolint CMake](https://github.com/MarcoSchaeferT/megamol-prolint-InVADo/blob/main/plugins/prolint/CMakeLists.txt) I hope that helps to clarify the setup process. Don't hesitate to ask if you have further questions.
